version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./config/loki.yml:/etc/loki/local-config.yml
      - ./config/loki-rules.yml:/etc/loki/rules/fake/rules.yml
    networks:
      - loki
  
  mimir:
    image: grafana/mimir:2.10.3
    container_name: mimir
    ports:
      - "9009:9009"
    command: -config.file=/etc/mimir/local-config.yml
    volumes:
      - ./config/mimir.yml:/etc/mimir/local-config.yml
      # - ./config/loki-rules.yml:/etc/loki/rules/fake/rules.yml
    networks:
      - loki

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/config.yml
    networks:
      - loki

  k6:
    build: ./k6
    image: k6loki
    command:
      - 'k6'
      - 'run'
      - '/scripts/test-logs.js'
    ports:
      - "6565:6565"
    volumes:
      - ./config/test-logs.js:/scripts/test-logs.js
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana-ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    networks:
      - loki

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9001:9001"
    networks:
      - loki

  miniobuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/loki;
      /usr/bin/mc anonymous set public minio/loki;
      /usr/bin/mc mb minio/mimir;
      /usr/bin/mc anonymous set public minio/mimir;
      exit 0;
      "
    networks:
      - loki
